# pseudo targets should be explicitely stated in the Makefile.
.PHONY : all clean

all: myFinder

hello_world: myFinder.cpp
	g++ myFinder.cpp -o myFinder

# delete everything execpt source files
clean:
	rm myFinder
	
